# Generated by Django 5.2.13 on 2026-05-04 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_retailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
