# Generated by Django 5.2.13 on 2026-05-05 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productlink_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
