# Generated by Django 6.0.5 on 2026-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_pricehistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlink',
            name='next_update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productlink',
            name='update_interval_hours',
            field=models.IntegerField(default=2),
        ),
    ]
