# Generated by Django 6.0.5 on 2026-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productlink_next_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='next_update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
