# Generated by Django 6.0.5 on 2026-05-19 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_employeeshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='days',
            field=models.ManyToManyField(help_text='Select your working days:', related_name='shifts', to='users.workday'),
        ),
    ]
