# Generated by Django 5.2.13 on 2026-05-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproducttracking',
            name='product_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by_users', to='products.productlink'),
        ),
        migrations.AddField(
            model_name='userproducttracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_product_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_notifications', to='tracking.userproducttracking'),
        ),
        migrations.AddConstraint(
            model_name='userproducttracking',
            constraint=models.UniqueConstraint(fields=('user', 'product_link'), name='unique_user_product_tracking'),
        ),
    ]
