# Generated by Django 6.0.5 on 2026-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducttracking',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
