# Generated by Django 6.0.5 on 2026-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_userproducttracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducttracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
