# Generated by Django 6.0.5 on 2026-05-06 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_userproducttracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducttracking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
